version: '3'
services:
  postgres_db40:
    image: postgres:14-alpine
    container_name: "postgres40"
    environment:
      - "POSTGRES_PASSWORD=123potato"
      - "POSTGRES_DB=ligia_diazdb"
      - "POSTGRES_USER=ligia_diaz"
    ports:
      - "10040:5540"
    volumes:
      - "/home/ligia_diaz/postgres:/usr/src/postgres"
    networks:
      - our-library-net
    command: -p 5540

  web40:
    build: .
    command: bash -c "python manage.py makemigrations && python manage.py migrate && pytest && python manage.py runserver 0.0.0.0:8040"
    container_name: "django40"
    depends_on: 
      - postgres_db40
    environment:
      - "PSQL_DBNAME=ligia_diazdb"
      - "PSQL_USERNAME=ligia_diaz"
      - "PSQL_PASS=123potato"
      - "PSQL_HOST=172.24.0.7" # You must use the previous command in order to get this HOST
      - "PSQL_PORT=5540"
    volumes:
    # "RUTA/DEL/SERVIDOR:RUTA/DENTRO/DEL/CONTENEDOR"
      - "/home/ligia_diaz/djangoassignment/django-assignment-sdhirashi/Django-REST-Exercise:/usr/src/django/library"
    ports:
      - "9040:8040"
    networks:
      - our-library-net

networks:
  our-library-net:
    external: true
    driver: bridge