# Generated by Django 4.0.3 on 2022-04-03 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='BookGenres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookname', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='BookWithGenre', to='books.book')),
                ('selectedgenre', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='GenreWithBook', to='books.genre')),
            ],
        ),
    ]
